FROM node:18

# Creating the app directory
WORKDIR /app 

# installing all dependensies
COPY package*.json ./

# running npm install
RUN npm install

# bundling app from curreent to current working directory
COPY . .
EXPOSE 3000
CMD ["node", "app.js"]